// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC64C03eBmWqsVfwhlo-z5AsGGRGgPPPBA',
    appId: '1:450042224208:web:b3da3a1ee502971ecc7b55',
    messagingSenderId: '450042224208',
    projectId: 'manovecina-564b4',
    authDomain: 'manovecina-564b4.firebaseapp.com',
    storageBucket: 'manovecina-564b4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGfr_ek_e7kG-EPw43jasxhT1LiIk1E4Q',
    appId: '1:450042224208:android:c4f5d9177b07f1b2cc7b55',
    messagingSenderId: '450042224208',
    projectId: 'manovecina-564b4',
    storageBucket: 'manovecina-564b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6GzeggU03JmgzeJzntseuOc-Y0L4xeV0',
    appId: '1:450042224208:ios:5b0298754df43176cc7b55',
    messagingSenderId: '450042224208',
    projectId: 'manovecina-564b4',
    storageBucket: 'manovecina-564b4.firebasestorage.app',
    iosBundleId: 'com.example.manovecina',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6GzeggU03JmgzeJzntseuOc-Y0L4xeV0',
    appId: '1:450042224208:ios:5b0298754df43176cc7b55',
    messagingSenderId: '450042224208',
    projectId: 'manovecina-564b4',
    storageBucket: 'manovecina-564b4.firebasestorage.app',
    iosBundleId: 'com.example.manovecina',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC64C03eBmWqsVfwhlo-z5AsGGRGgPPPBA',
    appId: '1:450042224208:web:e9284bdcbafd8078cc7b55',
    messagingSenderId: '450042224208',
    projectId: 'manovecina-564b4',
    authDomain: 'manovecina-564b4.firebaseapp.com',
    storageBucket: 'manovecina-564b4.firebasestorage.app',
  );
}
